<?php
/**
 * RecoveryApi
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VaultumSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use VaultumSDK\ApiException;
use VaultumSDK\Configuration;
use VaultumSDK\FormDataProcessor;
use VaultumSDK\HeaderSelector;
use VaultumSDK\ObjectSerializer;

/**
 * RecoveryApi Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecoveryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiRecoveryAccountStatusGet' => [
            'application/json',
        ],
        'apiRecoveryCancelPost' => [
            'application/json',
        ],
        'apiRecoveryExecutePost' => [
            'application/json',
        ],
        'apiRecoveryInitiatePost' => [
            'application/json',
        ],
        'apiRecoverySupportPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiRecoveryAccountStatusGet
     *
     * Get recovery status
     *
     * @param  string $account account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\RecoveryStatus
     */
    public function apiRecoveryAccountStatusGet($account, string $contentType = self::contentTypes['apiRecoveryAccountStatusGet'][0])
    {
        list($response) = $this->apiRecoveryAccountStatusGetWithHttpInfo($account, $contentType);
        return $response;
    }

    /**
     * Operation apiRecoveryAccountStatusGetWithHttpInfo
     *
     * Get recovery status
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\RecoveryStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiRecoveryAccountStatusGetWithHttpInfo($account, string $contentType = self::contentTypes['apiRecoveryAccountStatusGet'][0])
    {
        $request = $this->apiRecoveryAccountStatusGetRequest($account, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\RecoveryStatus',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\RecoveryStatus',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\RecoveryStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiRecoveryAccountStatusGetAsync
     *
     * Get recovery status
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryAccountStatusGetAsync($account, string $contentType = self::contentTypes['apiRecoveryAccountStatusGet'][0])
    {
        return $this->apiRecoveryAccountStatusGetAsyncWithHttpInfo($account, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiRecoveryAccountStatusGetAsyncWithHttpInfo
     *
     * Get recovery status
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryAccountStatusGetAsyncWithHttpInfo($account, string $contentType = self::contentTypes['apiRecoveryAccountStatusGet'][0])
    {
        $returnType = '\VaultumSDK\Model\RecoveryStatus';
        $request = $this->apiRecoveryAccountStatusGetRequest($account, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiRecoveryAccountStatusGet'
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiRecoveryAccountStatusGetRequest($account, string $contentType = self::contentTypes['apiRecoveryAccountStatusGet'][0])
    {

        // verify the required parameter 'account' is set
        if ($account === null || (is_array($account) && count($account) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account when calling apiRecoveryAccountStatusGet'
            );
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $account)) {
            throw new \InvalidArgumentException("invalid value for \"account\" when calling RecoveryApi.apiRecoveryAccountStatusGet, must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }
        

        $resourcePath = '/api/recovery/{account}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account !== null) {
            $resourcePath = str_replace(
                '{' . 'account' . '}',
                ObjectSerializer::toPathValue($account),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiRecoveryCancelPost
     *
     * Cancel recovery
     *
     * @param  \VaultumSDK\Model\RecoveryCancelRequest $recovery_cancel_request recovery_cancel_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryCancelPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiRecoveryCancelPost($recovery_cancel_request, string $contentType = self::contentTypes['apiRecoveryCancelPost'][0])
    {
        list($response) = $this->apiRecoveryCancelPostWithHttpInfo($recovery_cancel_request, $contentType);
        return $response;
    }

    /**
     * Operation apiRecoveryCancelPostWithHttpInfo
     *
     * Cancel recovery
     *
     * @param  \VaultumSDK\Model\RecoveryCancelRequest $recovery_cancel_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryCancelPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiRecoveryCancelPostWithHttpInfo($recovery_cancel_request, string $contentType = self::contentTypes['apiRecoveryCancelPost'][0])
    {
        $request = $this->apiRecoveryCancelPostRequest($recovery_cancel_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\RecoveryResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\RecoveryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\RecoveryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiRecoveryCancelPostAsync
     *
     * Cancel recovery
     *
     * @param  \VaultumSDK\Model\RecoveryCancelRequest $recovery_cancel_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryCancelPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryCancelPostAsync($recovery_cancel_request, string $contentType = self::contentTypes['apiRecoveryCancelPost'][0])
    {
        return $this->apiRecoveryCancelPostAsyncWithHttpInfo($recovery_cancel_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiRecoveryCancelPostAsyncWithHttpInfo
     *
     * Cancel recovery
     *
     * @param  \VaultumSDK\Model\RecoveryCancelRequest $recovery_cancel_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryCancelPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryCancelPostAsyncWithHttpInfo($recovery_cancel_request, string $contentType = self::contentTypes['apiRecoveryCancelPost'][0])
    {
        $returnType = '\VaultumSDK\Model\RecoveryResponse';
        $request = $this->apiRecoveryCancelPostRequest($recovery_cancel_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiRecoveryCancelPost'
     *
     * @param  \VaultumSDK\Model\RecoveryCancelRequest $recovery_cancel_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryCancelPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiRecoveryCancelPostRequest($recovery_cancel_request, string $contentType = self::contentTypes['apiRecoveryCancelPost'][0])
    {

        // verify the required parameter 'recovery_cancel_request' is set
        if ($recovery_cancel_request === null || (is_array($recovery_cancel_request) && count($recovery_cancel_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recovery_cancel_request when calling apiRecoveryCancelPost'
            );
        }


        $resourcePath = '/api/recovery/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recovery_cancel_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recovery_cancel_request));
            } else {
                $httpBody = $recovery_cancel_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiRecoveryExecutePost
     *
     * Execute recovery
     *
     * @param  \VaultumSDK\Model\RecoveryExecuteRequest $recovery_execute_request recovery_execute_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryExecutePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiRecoveryExecutePost($recovery_execute_request, string $contentType = self::contentTypes['apiRecoveryExecutePost'][0])
    {
        list($response) = $this->apiRecoveryExecutePostWithHttpInfo($recovery_execute_request, $contentType);
        return $response;
    }

    /**
     * Operation apiRecoveryExecutePostWithHttpInfo
     *
     * Execute recovery
     *
     * @param  \VaultumSDK\Model\RecoveryExecuteRequest $recovery_execute_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryExecutePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiRecoveryExecutePostWithHttpInfo($recovery_execute_request, string $contentType = self::contentTypes['apiRecoveryExecutePost'][0])
    {
        $request = $this->apiRecoveryExecutePostRequest($recovery_execute_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\RecoveryResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\RecoveryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\RecoveryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiRecoveryExecutePostAsync
     *
     * Execute recovery
     *
     * @param  \VaultumSDK\Model\RecoveryExecuteRequest $recovery_execute_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryExecutePostAsync($recovery_execute_request, string $contentType = self::contentTypes['apiRecoveryExecutePost'][0])
    {
        return $this->apiRecoveryExecutePostAsyncWithHttpInfo($recovery_execute_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiRecoveryExecutePostAsyncWithHttpInfo
     *
     * Execute recovery
     *
     * @param  \VaultumSDK\Model\RecoveryExecuteRequest $recovery_execute_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryExecutePostAsyncWithHttpInfo($recovery_execute_request, string $contentType = self::contentTypes['apiRecoveryExecutePost'][0])
    {
        $returnType = '\VaultumSDK\Model\RecoveryResponse';
        $request = $this->apiRecoveryExecutePostRequest($recovery_execute_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiRecoveryExecutePost'
     *
     * @param  \VaultumSDK\Model\RecoveryExecuteRequest $recovery_execute_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiRecoveryExecutePostRequest($recovery_execute_request, string $contentType = self::contentTypes['apiRecoveryExecutePost'][0])
    {

        // verify the required parameter 'recovery_execute_request' is set
        if ($recovery_execute_request === null || (is_array($recovery_execute_request) && count($recovery_execute_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recovery_execute_request when calling apiRecoveryExecutePost'
            );
        }


        $resourcePath = '/api/recovery/execute';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recovery_execute_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recovery_execute_request));
            } else {
                $httpBody = $recovery_execute_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiRecoveryInitiatePost
     *
     * Initiate social recovery
     *
     * @param  \VaultumSDK\Model\RecoveryRequest $recovery_request recovery_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryInitiatePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\RecoveryResponse
     */
    public function apiRecoveryInitiatePost($recovery_request, string $contentType = self::contentTypes['apiRecoveryInitiatePost'][0])
    {
        list($response) = $this->apiRecoveryInitiatePostWithHttpInfo($recovery_request, $contentType);
        return $response;
    }

    /**
     * Operation apiRecoveryInitiatePostWithHttpInfo
     *
     * Initiate social recovery
     *
     * @param  \VaultumSDK\Model\RecoveryRequest $recovery_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryInitiatePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\RecoveryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiRecoveryInitiatePostWithHttpInfo($recovery_request, string $contentType = self::contentTypes['apiRecoveryInitiatePost'][0])
    {
        $request = $this->apiRecoveryInitiatePostRequest($recovery_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\RecoveryResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\RecoveryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\RecoveryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiRecoveryInitiatePostAsync
     *
     * Initiate social recovery
     *
     * @param  \VaultumSDK\Model\RecoveryRequest $recovery_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryInitiatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryInitiatePostAsync($recovery_request, string $contentType = self::contentTypes['apiRecoveryInitiatePost'][0])
    {
        return $this->apiRecoveryInitiatePostAsyncWithHttpInfo($recovery_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiRecoveryInitiatePostAsyncWithHttpInfo
     *
     * Initiate social recovery
     *
     * @param  \VaultumSDK\Model\RecoveryRequest $recovery_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryInitiatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoveryInitiatePostAsyncWithHttpInfo($recovery_request, string $contentType = self::contentTypes['apiRecoveryInitiatePost'][0])
    {
        $returnType = '\VaultumSDK\Model\RecoveryResponse';
        $request = $this->apiRecoveryInitiatePostRequest($recovery_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiRecoveryInitiatePost'
     *
     * @param  \VaultumSDK\Model\RecoveryRequest $recovery_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoveryInitiatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiRecoveryInitiatePostRequest($recovery_request, string $contentType = self::contentTypes['apiRecoveryInitiatePost'][0])
    {

        // verify the required parameter 'recovery_request' is set
        if ($recovery_request === null || (is_array($recovery_request) && count($recovery_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recovery_request when calling apiRecoveryInitiatePost'
            );
        }


        $resourcePath = '/api/recovery/initiate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recovery_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recovery_request));
            } else {
                $httpBody = $recovery_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiRecoverySupportPost
     *
     * Support active recovery
     *
     * @param  \VaultumSDK\Model\RecoverySupportRequest $recovery_support_request recovery_support_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoverySupportPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiRecoverySupportPost($recovery_support_request, string $contentType = self::contentTypes['apiRecoverySupportPost'][0])
    {
        list($response) = $this->apiRecoverySupportPostWithHttpInfo($recovery_support_request, $contentType);
        return $response;
    }

    /**
     * Operation apiRecoverySupportPostWithHttpInfo
     *
     * Support active recovery
     *
     * @param  \VaultumSDK\Model\RecoverySupportRequest $recovery_support_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoverySupportPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\RecoveryResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiRecoverySupportPostWithHttpInfo($recovery_support_request, string $contentType = self::contentTypes['apiRecoverySupportPost'][0])
    {
        $request = $this->apiRecoverySupportPostRequest($recovery_support_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\RecoveryResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\RecoveryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\RecoveryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiRecoverySupportPostAsync
     *
     * Support active recovery
     *
     * @param  \VaultumSDK\Model\RecoverySupportRequest $recovery_support_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoverySupportPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoverySupportPostAsync($recovery_support_request, string $contentType = self::contentTypes['apiRecoverySupportPost'][0])
    {
        return $this->apiRecoverySupportPostAsyncWithHttpInfo($recovery_support_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiRecoverySupportPostAsyncWithHttpInfo
     *
     * Support active recovery
     *
     * @param  \VaultumSDK\Model\RecoverySupportRequest $recovery_support_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoverySupportPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiRecoverySupportPostAsyncWithHttpInfo($recovery_support_request, string $contentType = self::contentTypes['apiRecoverySupportPost'][0])
    {
        $returnType = '\VaultumSDK\Model\RecoveryResponse';
        $request = $this->apiRecoverySupportPostRequest($recovery_support_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiRecoverySupportPost'
     *
     * @param  \VaultumSDK\Model\RecoverySupportRequest $recovery_support_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiRecoverySupportPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiRecoverySupportPostRequest($recovery_support_request, string $contentType = self::contentTypes['apiRecoverySupportPost'][0])
    {

        // verify the required parameter 'recovery_support_request' is set
        if ($recovery_support_request === null || (is_array($recovery_support_request) && count($recovery_support_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recovery_support_request when calling apiRecoverySupportPost'
            );
        }


        $resourcePath = '/api/recovery/support';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recovery_support_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recovery_support_request));
            } else {
                $httpBody = $recovery_support_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
