<?php
/**
 * SessionKeysApi
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VaultumSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use VaultumSDK\ApiException;
use VaultumSDK\Configuration;
use VaultumSDK\FormDataProcessor;
use VaultumSDK\HeaderSelector;
use VaultumSDK\ObjectSerializer;

/**
 * SessionKeysApi Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SessionKeysApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiSessionkeyGrantPost' => [
            'application/json',
        ],
        'apiSessionkeyRevokePost' => [
            'application/json',
        ],
        'apiSessionkeySelectorPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiSessionkeyGrantPost
     *
     * Grant session key
     *
     * @param  \VaultumSDK\Model\SessionKeyGrantRequest $session_key_grant_request session_key_grant_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyGrantPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiSessionkeyGrantPost($session_key_grant_request, string $contentType = self::contentTypes['apiSessionkeyGrantPost'][0])
    {
        list($response) = $this->apiSessionkeyGrantPostWithHttpInfo($session_key_grant_request, $contentType);
        return $response;
    }

    /**
     * Operation apiSessionkeyGrantPostWithHttpInfo
     *
     * Grant session key
     *
     * @param  \VaultumSDK\Model\SessionKeyGrantRequest $session_key_grant_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyGrantPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiSessionkeyGrantPostWithHttpInfo($session_key_grant_request, string $contentType = self::contentTypes['apiSessionkeyGrantPost'][0])
    {
        $request = $this->apiSessionkeyGrantPostRequest($session_key_grant_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\SessionKeyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiSessionkeyGrantPostAsync
     *
     * Grant session key
     *
     * @param  \VaultumSDK\Model\SessionKeyGrantRequest $session_key_grant_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyGrantPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeyGrantPostAsync($session_key_grant_request, string $contentType = self::contentTypes['apiSessionkeyGrantPost'][0])
    {
        return $this->apiSessionkeyGrantPostAsyncWithHttpInfo($session_key_grant_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiSessionkeyGrantPostAsyncWithHttpInfo
     *
     * Grant session key
     *
     * @param  \VaultumSDK\Model\SessionKeyGrantRequest $session_key_grant_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyGrantPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeyGrantPostAsyncWithHttpInfo($session_key_grant_request, string $contentType = self::contentTypes['apiSessionkeyGrantPost'][0])
    {
        $returnType = '\VaultumSDK\Model\SessionKeyResponse';
        $request = $this->apiSessionkeyGrantPostRequest($session_key_grant_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiSessionkeyGrantPost'
     *
     * @param  \VaultumSDK\Model\SessionKeyGrantRequest $session_key_grant_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyGrantPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiSessionkeyGrantPostRequest($session_key_grant_request, string $contentType = self::contentTypes['apiSessionkeyGrantPost'][0])
    {

        // verify the required parameter 'session_key_grant_request' is set
        if ($session_key_grant_request === null || (is_array($session_key_grant_request) && count($session_key_grant_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $session_key_grant_request when calling apiSessionkeyGrantPost'
            );
        }


        $resourcePath = '/api/sessionkey/grant';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($session_key_grant_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($session_key_grant_request));
            } else {
                $httpBody = $session_key_grant_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiSessionkeyRevokePost
     *
     * Revoke session key
     *
     * @param  \VaultumSDK\Model\SessionKeyRevokeRequest $session_key_revoke_request session_key_revoke_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyRevokePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiSessionkeyRevokePost($session_key_revoke_request, string $contentType = self::contentTypes['apiSessionkeyRevokePost'][0])
    {
        list($response) = $this->apiSessionkeyRevokePostWithHttpInfo($session_key_revoke_request, $contentType);
        return $response;
    }

    /**
     * Operation apiSessionkeyRevokePostWithHttpInfo
     *
     * Revoke session key
     *
     * @param  \VaultumSDK\Model\SessionKeyRevokeRequest $session_key_revoke_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyRevokePost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiSessionkeyRevokePostWithHttpInfo($session_key_revoke_request, string $contentType = self::contentTypes['apiSessionkeyRevokePost'][0])
    {
        $request = $this->apiSessionkeyRevokePostRequest($session_key_revoke_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\SessionKeyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiSessionkeyRevokePostAsync
     *
     * Revoke session key
     *
     * @param  \VaultumSDK\Model\SessionKeyRevokeRequest $session_key_revoke_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyRevokePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeyRevokePostAsync($session_key_revoke_request, string $contentType = self::contentTypes['apiSessionkeyRevokePost'][0])
    {
        return $this->apiSessionkeyRevokePostAsyncWithHttpInfo($session_key_revoke_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiSessionkeyRevokePostAsyncWithHttpInfo
     *
     * Revoke session key
     *
     * @param  \VaultumSDK\Model\SessionKeyRevokeRequest $session_key_revoke_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyRevokePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeyRevokePostAsyncWithHttpInfo($session_key_revoke_request, string $contentType = self::contentTypes['apiSessionkeyRevokePost'][0])
    {
        $returnType = '\VaultumSDK\Model\SessionKeyResponse';
        $request = $this->apiSessionkeyRevokePostRequest($session_key_revoke_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiSessionkeyRevokePost'
     *
     * @param  \VaultumSDK\Model\SessionKeyRevokeRequest $session_key_revoke_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeyRevokePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiSessionkeyRevokePostRequest($session_key_revoke_request, string $contentType = self::contentTypes['apiSessionkeyRevokePost'][0])
    {

        // verify the required parameter 'session_key_revoke_request' is set
        if ($session_key_revoke_request === null || (is_array($session_key_revoke_request) && count($session_key_revoke_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $session_key_revoke_request when calling apiSessionkeyRevokePost'
            );
        }


        $resourcePath = '/api/sessionkey/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($session_key_revoke_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($session_key_revoke_request));
            } else {
                $httpBody = $session_key_revoke_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiSessionkeySelectorPut
     *
     * Update session key selectors
     *
     * @param  \VaultumSDK\Model\SessionKeySelectorRequest $session_key_selector_request session_key_selector_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeySelectorPut'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiSessionkeySelectorPut($session_key_selector_request, string $contentType = self::contentTypes['apiSessionkeySelectorPut'][0])
    {
        list($response) = $this->apiSessionkeySelectorPutWithHttpInfo($session_key_selector_request, $contentType);
        return $response;
    }

    /**
     * Operation apiSessionkeySelectorPutWithHttpInfo
     *
     * Update session key selectors
     *
     * @param  \VaultumSDK\Model\SessionKeySelectorRequest $session_key_selector_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeySelectorPut'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\SessionKeyResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiSessionkeySelectorPutWithHttpInfo($session_key_selector_request, string $contentType = self::contentTypes['apiSessionkeySelectorPut'][0])
    {
        $request = $this->apiSessionkeySelectorPutRequest($session_key_selector_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\SessionKeyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\SessionKeyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiSessionkeySelectorPutAsync
     *
     * Update session key selectors
     *
     * @param  \VaultumSDK\Model\SessionKeySelectorRequest $session_key_selector_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeySelectorPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeySelectorPutAsync($session_key_selector_request, string $contentType = self::contentTypes['apiSessionkeySelectorPut'][0])
    {
        return $this->apiSessionkeySelectorPutAsyncWithHttpInfo($session_key_selector_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiSessionkeySelectorPutAsyncWithHttpInfo
     *
     * Update session key selectors
     *
     * @param  \VaultumSDK\Model\SessionKeySelectorRequest $session_key_selector_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeySelectorPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiSessionkeySelectorPutAsyncWithHttpInfo($session_key_selector_request, string $contentType = self::contentTypes['apiSessionkeySelectorPut'][0])
    {
        $returnType = '\VaultumSDK\Model\SessionKeyResponse';
        $request = $this->apiSessionkeySelectorPutRequest($session_key_selector_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiSessionkeySelectorPut'
     *
     * @param  \VaultumSDK\Model\SessionKeySelectorRequest $session_key_selector_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiSessionkeySelectorPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiSessionkeySelectorPutRequest($session_key_selector_request, string $contentType = self::contentTypes['apiSessionkeySelectorPut'][0])
    {

        // verify the required parameter 'session_key_selector_request' is set
        if ($session_key_selector_request === null || (is_array($session_key_selector_request) && count($session_key_selector_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $session_key_selector_request when calling apiSessionkeySelectorPut'
            );
        }


        $resourcePath = '/api/sessionkey/selector';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($session_key_selector_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($session_key_selector_request));
            } else {
                $httpBody = $session_key_selector_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
