<?php
/**
 * SpendingLimitsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VaultumSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use VaultumSDK\ApiException;
use VaultumSDK\Configuration;
use VaultumSDK\FormDataProcessor;
use VaultumSDK\HeaderSelector;
use VaultumSDK\ObjectSerializer;

/**
 * SpendingLimitsApi Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpendingLimitsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiLimitsAccountStatusGet' => [
            'application/json',
        ],
        'apiLimitsBypassPost' => [
            'application/json',
        ],
        'apiLimitsSetPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiLimitsAccountStatusGet
     *
     * Get spending limits
     *
     * @param  string $account account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\SpendingLimitsStatus
     */
    public function apiLimitsAccountStatusGet($account, string $contentType = self::contentTypes['apiLimitsAccountStatusGet'][0])
    {
        list($response) = $this->apiLimitsAccountStatusGetWithHttpInfo($account, $contentType);
        return $response;
    }

    /**
     * Operation apiLimitsAccountStatusGetWithHttpInfo
     *
     * Get spending limits
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\SpendingLimitsStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiLimitsAccountStatusGetWithHttpInfo($account, string $contentType = self::contentTypes['apiLimitsAccountStatusGet'][0])
    {
        $request = $this->apiLimitsAccountStatusGetRequest($account, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\SpendingLimitsStatus',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\SpendingLimitsStatus',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\SpendingLimitsStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiLimitsAccountStatusGetAsync
     *
     * Get spending limits
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsAccountStatusGetAsync($account, string $contentType = self::contentTypes['apiLimitsAccountStatusGet'][0])
    {
        return $this->apiLimitsAccountStatusGetAsyncWithHttpInfo($account, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiLimitsAccountStatusGetAsyncWithHttpInfo
     *
     * Get spending limits
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsAccountStatusGetAsyncWithHttpInfo($account, string $contentType = self::contentTypes['apiLimitsAccountStatusGet'][0])
    {
        $returnType = '\VaultumSDK\Model\SpendingLimitsStatus';
        $request = $this->apiLimitsAccountStatusGetRequest($account, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiLimitsAccountStatusGet'
     *
     * @param  string $account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsAccountStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiLimitsAccountStatusGetRequest($account, string $contentType = self::contentTypes['apiLimitsAccountStatusGet'][0])
    {

        // verify the required parameter 'account' is set
        if ($account === null || (is_array($account) && count($account) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account when calling apiLimitsAccountStatusGet'
            );
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $account)) {
            throw new \InvalidArgumentException("invalid value for \"account\" when calling SpendingLimitsApi.apiLimitsAccountStatusGet, must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }
        

        $resourcePath = '/api/limits/{account}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account !== null) {
            $resourcePath = str_replace(
                '{' . 'account' . '}',
                ObjectSerializer::toPathValue($account),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiLimitsBypassPost
     *
     * Toggle owner bypass
     *
     * @param  \VaultumSDK\Model\BypassToggleRequest $bypass_toggle_request bypass_toggle_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsBypassPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\BypassStatusResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiLimitsBypassPost($bypass_toggle_request, string $contentType = self::contentTypes['apiLimitsBypassPost'][0])
    {
        list($response) = $this->apiLimitsBypassPostWithHttpInfo($bypass_toggle_request, $contentType);
        return $response;
    }

    /**
     * Operation apiLimitsBypassPostWithHttpInfo
     *
     * Toggle owner bypass
     *
     * @param  \VaultumSDK\Model\BypassToggleRequest $bypass_toggle_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsBypassPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\BypassStatusResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiLimitsBypassPostWithHttpInfo($bypass_toggle_request, string $contentType = self::contentTypes['apiLimitsBypassPost'][0])
    {
        $request = $this->apiLimitsBypassPostRequest($bypass_toggle_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\BypassStatusResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\BypassStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\BypassStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiLimitsBypassPostAsync
     *
     * Toggle owner bypass
     *
     * @param  \VaultumSDK\Model\BypassToggleRequest $bypass_toggle_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsBypassPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsBypassPostAsync($bypass_toggle_request, string $contentType = self::contentTypes['apiLimitsBypassPost'][0])
    {
        return $this->apiLimitsBypassPostAsyncWithHttpInfo($bypass_toggle_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiLimitsBypassPostAsyncWithHttpInfo
     *
     * Toggle owner bypass
     *
     * @param  \VaultumSDK\Model\BypassToggleRequest $bypass_toggle_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsBypassPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsBypassPostAsyncWithHttpInfo($bypass_toggle_request, string $contentType = self::contentTypes['apiLimitsBypassPost'][0])
    {
        $returnType = '\VaultumSDK\Model\BypassStatusResponse';
        $request = $this->apiLimitsBypassPostRequest($bypass_toggle_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiLimitsBypassPost'
     *
     * @param  \VaultumSDK\Model\BypassToggleRequest $bypass_toggle_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsBypassPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiLimitsBypassPostRequest($bypass_toggle_request, string $contentType = self::contentTypes['apiLimitsBypassPost'][0])
    {

        // verify the required parameter 'bypass_toggle_request' is set
        if ($bypass_toggle_request === null || (is_array($bypass_toggle_request) && count($bypass_toggle_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bypass_toggle_request when calling apiLimitsBypassPost'
            );
        }


        $resourcePath = '/api/limits/bypass';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($bypass_toggle_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($bypass_toggle_request));
            } else {
                $httpBody = $bypass_toggle_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiLimitsSetPost
     *
     * Set spending limit
     *
     * @param  \VaultumSDK\Model\SpendingLimitRequest $spending_limit_request spending_limit_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsSetPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \VaultumSDK\Model\SpendingLimitResponse|\VaultumSDK\Model\InlineObject
     */
    public function apiLimitsSetPost($spending_limit_request, string $contentType = self::contentTypes['apiLimitsSetPost'][0])
    {
        list($response) = $this->apiLimitsSetPostWithHttpInfo($spending_limit_request, $contentType);
        return $response;
    }

    /**
     * Operation apiLimitsSetPostWithHttpInfo
     *
     * Set spending limit
     *
     * @param  \VaultumSDK\Model\SpendingLimitRequest $spending_limit_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsSetPost'] to see the possible values for this operation
     *
     * @throws \VaultumSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \VaultumSDK\Model\SpendingLimitResponse|\VaultumSDK\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiLimitsSetPostWithHttpInfo($spending_limit_request, string $contentType = self::contentTypes['apiLimitsSetPost'][0])
    {
        $request = $this->apiLimitsSetPostRequest($spending_limit_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\SpendingLimitResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VaultumSDK\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VaultumSDK\Model\SpendingLimitResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\SpendingLimitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VaultumSDK\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiLimitsSetPostAsync
     *
     * Set spending limit
     *
     * @param  \VaultumSDK\Model\SpendingLimitRequest $spending_limit_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsSetPostAsync($spending_limit_request, string $contentType = self::contentTypes['apiLimitsSetPost'][0])
    {
        return $this->apiLimitsSetPostAsyncWithHttpInfo($spending_limit_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiLimitsSetPostAsyncWithHttpInfo
     *
     * Set spending limit
     *
     * @param  \VaultumSDK\Model\SpendingLimitRequest $spending_limit_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiLimitsSetPostAsyncWithHttpInfo($spending_limit_request, string $contentType = self::contentTypes['apiLimitsSetPost'][0])
    {
        $returnType = '\VaultumSDK\Model\SpendingLimitResponse';
        $request = $this->apiLimitsSetPostRequest($spending_limit_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiLimitsSetPost'
     *
     * @param  \VaultumSDK\Model\SpendingLimitRequest $spending_limit_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiLimitsSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiLimitsSetPostRequest($spending_limit_request, string $contentType = self::contentTypes['apiLimitsSetPost'][0])
    {

        // verify the required parameter 'spending_limit_request' is set
        if ($spending_limit_request === null || (is_array($spending_limit_request) && count($spending_limit_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $spending_limit_request when calling apiLimitsSetPost'
            );
        }


        $resourcePath = '/api/limits/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($spending_limit_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($spending_limit_request));
            } else {
                $httpBody = $spending_limit_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
