<?php
/**
 * OperationState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VaultumSDK\Model;
use \VaultumSDK\ObjectSerializer;

/**
 * OperationState Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationState
{
    /**
     * Possible values of this enum
     */
    public const QUEUED = 'queued';

    public const SENT = 'sent';

    public const SUCCESS = 'success';

    public const FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUEUED,
            self::SENT,
            self::SUCCESS,
            self::FAILED
        ];
    }
}


