<?php
/**
 * RecoveryApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace VaultumSDK\Test\Api;

use \VaultumSDK\Configuration;
use \VaultumSDK\ApiException;
use \VaultumSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecoveryApiTest Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecoveryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiRecoveryAccountStatusGet
     *
     * Get recovery status.
     *
     */
    public function testApiRecoveryAccountStatusGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiRecoveryCancelPost
     *
     * Cancel recovery.
     *
     */
    public function testApiRecoveryCancelPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiRecoveryExecutePost
     *
     * Execute recovery.
     *
     */
    public function testApiRecoveryExecutePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiRecoveryInitiatePost
     *
     * Initiate social recovery.
     *
     */
    public function testApiRecoveryInitiatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiRecoverySupportPost
     *
     * Support active recovery.
     *
     */
    public function testApiRecoverySupportPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
