<?php
/**
 * SessionKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vaultum API
 *
 * Backend API for Vaultum smart wallet operations
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace VaultumSDK\Test\Api;

use \VaultumSDK\Configuration;
use \VaultumSDK\ApiException;
use \VaultumSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SessionKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  VaultumSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SessionKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiSessionkeyGrantPost
     *
     * Grant session key.
     *
     */
    public function testApiSessionkeyGrantPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiSessionkeyRevokePost
     *
     * Revoke session key.
     *
     */
    public function testApiSessionkeyRevokePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiSessionkeySelectorPut
     *
     * Update session key selectors.
     *
     */
    public function testApiSessionkeySelectorPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
